---
  - name: Create GTM HTTPS Monitor
    bigip_gtm_monitor_https:
      provider: "{{ provider }}"
      name: "{{ item['domain'] }}-HTTPS-GTM-MONITOR"
      state: present
      send: "{{ item['monitor_method'] }} {{ item['monitor_path'] }} HTTP/1.1\\r\\nHost: {{ item['domain'] }}\\r\\nConnection: close\\r\\n\\r\\n"
      receive: "{{ item['receive_string'] }}"
    run_once: true
