---
  - name: Create LTM Policy Draft
    bigip_policy:
      provider: "{{ provider }}"
      name: "{{ vip_prefix }}-{{ policy_port | default(443) }}-POLICY"
      state: draft
      strategy: best
