---
- name: Create/Update HTTP Monitor
  bigip_monitor_http:
    provider: "{{ provider }}"
    name: "{{ item['domain'] }}-{{ item['protocol'] }}-MONITOR"
    state:  present
    send: "{{ item['monitor_method'] }} {{ item['monitor_path'] }} HTTP/1.1\\r\\nHost: {{ item['domain'] }}\\r\\nConnection: close\\r\\n\\r\\n"
    receive: "{{ item['receive_string'] }}"